### PR TITLE
Add python constraints

### PR DESCRIPTION
**Pull request by xylar**
Also add xylar as a maintainer and add `pip check`.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I'm running into issues with `pip check` because of this package downstream in:
https://github.com/conda-forge/apache-airflow-providers-sendgrid-feedstock/pull/16

**Comment by xylar** [comment]
@mariusvniekerk, would you be willing to review and merge this?

**Comment by xylar** [comment]
Then, I would be glad to take over maintenance.

**Comment by xylar** [comment]
@mariusvniekerk, just checking again if you'd be willing to merge this.

**Comment by xylar** [comment]
@conda-forge/core, it seems like the maintainers here don't have the time and/or interest to maintain this feedstock.  Would someone be willing to merge this so I can take over?

**Comment by wolfv** [comment]
Thanks @xylar

**Comment by xylar** [comment]
@wolfv, thank you as well!

**Pull request merged**
